webtitle: 'SuQing’s Page' # 首页标题

title: 'SuQing’s Page' # 页面 title 标签的显示内容
description: '欢迎来到苏轻的个人领域！' # 网站简介
keywords: '苏轻, 个人, 博客, 空间, Java, JavaScript, HTML' # 网站关键词
url: 'https://suqing.fun' # 网站域名


# 是否开启博主关于信息
about: true
aboutyou: ''
portraits: '/assets/suqing.jpg' # 头像
# 是否开启博主信息卡片
author: true
name: 'SuQing'
NickName: '阿轻'
bio: 'QQ：874717373' # 个人简历

# 导航栏
nav: 
  诗酒趁年华: '/'
  时间线: '/timeline'
  认识我: '/about'
  标签页: '/tags'
  友情链: '/link'

links: #友情链接
  武神传说工具包: '/wsmud'
  小炒肉 Blog: "https://jicki.me"

paginate: 5 # 分页
paginatepath: ['page:num']
footer: # 页脚
  since: 2017

markdown: kramdown # Markdown
kramdown:
  input: GFM
# - # - # - # - # - # - # - # - # - # - # - # - # - # - # - # - # - # - #
highlighter: rouge # 代码高亮
pygmentsTheme: 'perldoc'
# 代码高亮主题使用pygments主题，以下任选一个:
# autumn\default\emacs\friendly\manni\murphy\pastie\perldoc\tango
# - # - # - # - # - # - # - # - # - # - # - # - # - # - # - # - # - # - #

# 头信息备选颜色
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
# 该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量






SNS: false
SNS-icon: #['facebook', 'weibo', 'QQ', 'github', 'Dribbble', 'twitter', 'instagram', 'weixin']
  mail: 'mailto:874717373@qq.com'
  # 你的微信图片文件的地址
  #weixin: '' # your wechat image file path
  # 你的QQ图片文件的地址
  QQ: '' # your QQ image file path
  #weibo: ''
  #instagram: ''
  #twitter: ''
  github: 'https://github.com/emeisuqing'
  #Dribbble: ''
  #facebook: ''
  #Google: ''
  #zhihu: ''
  #juejin: ''
  #twitch: ''

# 评论系统
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: 'yMTAyMC8zNDI2OS8xMDgwNg==' # MTAMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: false
social-share-items: ['qq', 'qzone', 'wechat', 'weibo', 'facebook']